"use client";

import { Plus } from "lucide-react";
import { useActionState } from "react";
import { createCategory, updateCategoryStatus, type AdminOperationState } from "@/server/actions/admin-operations";

type Category = { id: string; name: string; slug: string; description: string | null; isActive: boolean; reportCount: number };
const initialState: AdminOperationState = {};

function CategoryStatus({ category }: { category: Category }) {
  const [state, formAction] = useActionState(updateCategoryStatus, initialState);
  return <form action={formAction} className="flex flex-col items-start gap-2"><input name="categoryId" type="hidden" value={category.id} /><input name="isActive" type="hidden" value={category.isActive ? "false" : "true"} /><button className={category.isActive ? "rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700 hover:bg-rose-50" : "rounded-lg border border-brand/30 px-3 py-2 text-xs font-bold text-brand hover:bg-brand-soft"} type="submit">{category.isActive ? "Deactivate" : "Activate"}</button>{state.message && <p className="text-xs text-rose-700">{state.message}</p>}{state.success && <p className="text-xs text-brand">{state.success}</p>}</form>;
}

export function CategoryManagement({ categories }: { categories: Category[] }) {
  const [state, formAction] = useActionState(createCategory, initialState);
  return <div className="space-y-8"><section className="rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><Plus aria-hidden="true" size={19} /></span><div><h2 className="font-bold text-brand-dark">Add issue category</h2><p className="mt-1 text-sm text-muted">Inactive categories are kept for existing reports but cannot be selected for new reports.</p></div></div><form action={formAction} className="mt-5 grid gap-4 md:grid-cols-[1fr_2fr_auto]"><label className="text-sm font-bold text-brand-dark">Name<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" name="name" required /></label><label className="text-sm font-bold text-brand-dark">Description<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" name="description" /></label><button className="self-end rounded-full bg-brand px-5 py-3 text-sm font-bold text-white hover:bg-brand-dark" type="submit">Add category</button><div className="md:col-span-3">{state.errors?.name?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.errors?.description?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.message && <p className="mt-1 text-sm text-rose-700">{state.message}</p>}{state.success && <p className="mt-1 text-sm text-brand">{state.success}</p>}</div></form></section><section className="overflow-x-auto rounded-2xl border border-border bg-surface"><table className="w-full min-w-3xl text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-wider text-muted"><tr><th className="p-4">Category</th><th className="p-4">Slug</th><th className="p-4">Reports</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-border">{categories.map((category) => <tr className="align-top" key={category.id}><td className="p-4"><p className="font-bold text-brand-dark">{category.name}</p>{category.description && <p className="mt-1 max-w-md text-xs leading-5 text-muted">{category.description}</p>}</td><td className="p-4 font-mono text-xs text-muted">{category.slug}</td><td className="p-4">{category.reportCount}</td><td className="p-4"><span className={category.isActive ? "rounded-full bg-brand-soft px-2.5 py-1 text-xs font-bold text-brand-dark" : "rounded-full bg-surface-muted px-2.5 py-1 text-xs font-bold text-muted"}>{category.isActive ? "Active" : "Inactive"}</span></td><td className="p-4"><CategoryStatus category={category} /></td></tr>)}</tbody></table></section></div>;
}
