"use client";

import { Plus, UsersRound } from "lucide-react";
import { useActionState } from "react";
import { createResponseTeam, updateResponseTeam, type AdminOperationState } from "@/server/actions/admin-operations";

type StaffMember = { id: string; name: string; email: string };
type Team = { id: string; name: string; contactEmail: string | null; isActive: boolean; memberIds: string[]; reportCount: number };
const initialState: AdminOperationState = {};

function MemberPicker({ staff, selectedIds }: { staff: StaffMember[]; selectedIds: string[] }) {
  if (staff.length === 0) return <p className="text-xs text-muted">Create a staff account first, then assign it to this team.</p>;
  return <div className="mt-2 grid gap-2 sm:grid-cols-2">{staff.map((person) => <label className="flex items-center gap-2 rounded-lg border border-border bg-surface px-3 py-2 text-xs text-brand-dark" key={person.id}><input defaultChecked={selectedIds.includes(person.id)} name="memberIds" type="checkbox" value={person.id} /><span><span className="block font-bold">{person.name}</span><span className="text-muted">{person.email}</span></span></label>)}</div>;
}

function TeamEditor({ team, staff }: { team: Team; staff: StaffMember[] }) {
  const [state, formAction] = useActionState(updateResponseTeam, initialState);
  return <article className="rounded-2xl border border-border bg-surface p-5"><form action={formAction} className="grid gap-4"><input name="teamId" type="hidden" value={team.id} /><label className="text-sm font-bold text-brand-dark">Team name<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" defaultValue={team.name} name="name" required /></label><label className="text-sm font-bold text-brand-dark">Contact email<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" defaultValue={team.contactEmail ?? ""} name="contactEmail" type="email" /></label><label className="flex items-center gap-2 text-sm font-bold text-brand-dark"><input defaultChecked={team.isActive} name="isActive" type="checkbox" value="true" /><span>Active and available for assignments</span></label><input name="isActive" type="hidden" value="false" /><fieldset><legend className="text-sm font-bold text-brand-dark">Team members</legend><MemberPicker selectedIds={team.memberIds} staff={staff} /></fieldset><p className="text-xs text-muted">{team.reportCount} report(s) currently assigned to this team.</p>{state.errors?.name?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.errors?.contactEmail?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.message && <p className="text-sm text-rose-700">{state.message}</p>}{state.success && <p className="text-sm text-brand">{state.success}</p>}<button className="w-fit rounded-full bg-brand px-4 py-2 text-sm font-bold text-white hover:bg-brand-dark" type="submit">Save team</button></form></article>;
}

export function ResponseTeamManagement({ teams, staff }: { teams: Team[]; staff: StaffMember[] }) {
  const [state, formAction] = useActionState(createResponseTeam, initialState);
  return <div className="space-y-8"><section className="rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><UsersRound aria-hidden="true" size={19} /></span><div><h2 className="font-bold text-brand-dark">Create response team</h2><p className="mt-1 text-sm text-muted">A team can be assigned to verified reports and can include active staff members.</p></div></div><form action={formAction} className="mt-5 grid gap-4"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold text-brand-dark">Team name<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" name="name" required /></label><label className="text-sm font-bold text-brand-dark">Contact email<input className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" name="contactEmail" type="email" /></label></div><fieldset><legend className="text-sm font-bold text-brand-dark">Initial members</legend><MemberPicker selectedIds={[]} staff={staff} /></fieldset>{state.errors?.name?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.errors?.contactEmail?.map((error) => <p className="text-xs text-rose-700" key={error}>{error}</p>)}{state.message && <p className="text-sm text-rose-700">{state.message}</p>}{state.success && <p className="text-sm text-brand">{state.success}</p>}<button className="w-fit rounded-full bg-brand px-5 py-3 text-sm font-bold text-white hover:bg-brand-dark" type="submit"><Plus aria-hidden="true" className="mr-1 inline" size={16} /> Create team</button></form></section><section className="grid gap-4 lg:grid-cols-2">{teams.map((team) => <TeamEditor key={team.id} staff={staff} team={team} />)}{teams.length === 0 && <div className="rounded-2xl border border-dashed border-border bg-surface p-10 text-center text-sm text-muted">No response teams have been created.</div>}</section></div>;
}
