import { ArrowLeft } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { StatusBadge } from "@/components/ui/status-badge";
import { requireRole } from "@/lib/auth/user";
import { getPrisma } from "@/lib/db/prisma";
import { getEvidenceUrl } from "@/lib/storage/evidence";
import { transitionReport } from "@/server/actions/reports";

const labels = { DRAFT: "Draft", SUBMITTED: "Submitted", VERIFIED: "Verified", IN_PROGRESS: "In Progress", RESOLVED: "Resolved", REJECTED: "Rejected", CANCELLED: "Cancelled" } as const;
const button = "rounded-full bg-brand px-4 py-2 text-sm font-bold text-white";
export const dynamic = "force-dynamic";

export default async function StaffReportPage({ params }: { params: Promise<{ reportId: string }> }) {
  await requireRole(["STAFF", "ADMIN"]);
  const { reportId } = await params;
  const [report, teams, staff] = await Promise.all([
    getPrisma().report.findUnique({ where: { publicId: reportId }, include: { category: true, reporter: { select: { name: true } }, media: { orderBy: { createdAt: "asc" } }, statusHistory: { include: { actor: { select: { name: true } } }, orderBy: { createdAt: "asc" } } } }),
    getPrisma().responseTeam.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    getPrisma().user.findMany({ where: { role: { in: ["STAFF", "ADMIN"] }, status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
  ]);
  if (!report || report.status === "DRAFT") notFound();
  const evidence = await Promise.all(report.media.map(async (item) => ({ ...item, signedUrl: await getEvidenceUrl(item.objectKey) })));
  return <div className="mx-auto max-w-4xl"><Link className="inline-flex items-center gap-2 text-sm font-bold text-brand" href="/staff"><ArrowLeft size={16} /> Back to queue</Link><article className="mt-6 rounded-3xl border border-border bg-surface p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-mono text-xs font-bold text-brand">{report.publicId} · {report.category.name}</p><h1 className="mt-2 text-3xl font-bold text-brand-dark">{report.title}</h1><p className="mt-2 text-sm text-muted">{report.address} · Reported by {report.reporter.name}</p></div><StatusBadge status={labels[report.status]} /></div><p className="mt-8 border-t border-border pt-6 leading-7 text-muted">{report.description}</p>{evidence.length > 0 && <div className="mt-6 grid gap-3 sm:grid-cols-2">{evidence.map((item) => item.signedUrl ? <Image alt={item.altText ?? `Evidence for ${reportId}`} className="h-52 w-full rounded-2xl object-cover" height={520} key={item.id} src={item.signedUrl} unoptimized width={800} /> : null)}</div>}
  {report.status === "SUBMITTED" && <div className="mt-8 grid gap-4 rounded-2xl bg-surface-muted p-5 sm:grid-cols-2"><form action={transitionReport}><input name="reportId" type="hidden" value={reportId} /><input name="transition" type="hidden" value="verify" /><label className="text-sm font-bold" htmlFor="verify-note">Verification note</label><textarea className="mt-2 w-full rounded-xl border border-border p-3 text-sm" id="verify-note" name="note" placeholder="What was checked?" /><button className={`${button} mt-3`} type="submit">Verify report</button></form><form action={transitionReport}><input name="reportId" type="hidden" value={reportId} /><input name="transition" type="hidden" value="reject" /><label className="text-sm font-bold" htmlFor="reject-note">Rejection reason</label><textarea className="mt-2 w-full rounded-xl border border-border p-3 text-sm" id="reject-note" name="note" required /><button className="mt-3 rounded-full bg-red-700 px-4 py-2 text-sm font-bold text-white" type="submit">Reject report</button></form></div>}
  {report.status === "VERIFIED" && <div className="mt-8 space-y-4 rounded-2xl bg-surface-muted p-5"><form action={transitionReport} className="grid gap-3 sm:grid-cols-2"><input name="reportId" type="hidden" value={reportId} /><input name="transition" type="hidden" value="assign" /><select className="h-11 rounded-xl border border-border bg-surface px-3 text-sm" defaultValue={report.assignedTeamId ?? ""} name="assignedTeamId"><option value="">Choose team</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><select className="h-11 rounded-xl border border-border bg-surface px-3 text-sm" defaultValue={report.assignedStaffId ?? ""} name="assignedStaffId"><option value="">Choose staff member</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select><button className={`${button} sm:col-span-2`} type="submit">Save assignment</button></form><form action={transitionReport}><input name="reportId" type="hidden" value={reportId} /><input name="transition" type="hidden" value="start" /><input className="h-11 w-full rounded-xl border border-border bg-surface px-3 text-sm" name="note" placeholder="Work-start note (optional)" /><button className={`${button} mt-3`} type="submit">Start response work</button></form></div>}
  {report.status === "IN_PROGRESS" && <form action={transitionReport} className="mt-8 rounded-2xl border border-brand/10 bg-surface-muted p-5"><input name="reportId" type="hidden" value={reportId} /><input name="transition" type="hidden" value="resolve" /><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><label className="text-sm font-bold text-brand-dark" htmlFor="resolution-note">Resolution summary</label><p className="text-xs text-muted">This update will be visible to the resident.</p></div><textarea className="mt-3 min-h-28 w-full rounded-xl border border-border bg-surface p-3 text-sm" id="resolution-note" name="note" placeholder="Describe the completed work and outcome." required /><button className={`${button} mt-4`} type="submit">Mark resolved</button></form>}
  <section className="mt-8 border-t border-border pt-6"><h2 className="font-bold text-brand-dark">Activity history</h2><ol className="mt-4 space-y-3">{report.statusHistory.map((event) => <li className="text-sm text-muted" key={event.id}><span className="font-bold text-brand-dark">{labels[event.toStatus]}</span> by {event.actor?.name ?? "System"}{event.note ? ` - ${event.note}` : ""}</li>)}</ol></section></article></div>;
}
